name: Deploy on GH-Pages
on:
  push:
    branchs:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - uses: actions/cache@v2
        id: cache-modules
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - run: yarn
        if: steps.cache-modules.outputs.cache-hit != 'true'
      - run: yarn build
      - name: 🚀 Deploy (gh-pages)
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to
          FOLDER: dist-export # The folder the action should deploy
